#include "relay_decoder.h"
#include <string.h>
#include <limits.h>

/* solution weight: w(ˆe) = ∑_j (^e_j)*log(1-p_j)/p_j 
   lambda = error_prior
*/
static int solution_weight(const int *e_hat, const int lambda_j_0_int, int n){
    int i, w = 0;
    for (i = 0; i < n; i++){
        if (e_hat[i]) w += lambda_j_0_int;  // ω_j * e_j = (e_j = 1) ? ω_j : 0; so use if statement to avoid multiplication
    }
    return w;
}

int decode_relay(const int error[H_X_COLS], int lambda_j_0_int, uint32_t seed,
                 int e_hat_out[H_X_COLS], int *total_iters_out,
                 int *num_sol_out, int *legs_used_out){

    int i, r;

    /* ---- get check node & variable node's neighbor list ---- */
    int cn_neighbor[H_X_ROWS][CN_DEGREE];
    int vn_neighbor[H_X_COLS][VN_DEGREE];
    build_neighbor_list(cn_neighbor, vn_neighbor);
    
    /* ---- get syndrome ---- */
    int syndrome[H_X_ROWS];
    xor_for_matrix_mult(h_x, H_X_ROWS, H_X_COLS, error, syndrome);

    /* ---- initialize error-prior ---- 
    In code-level H, we assume all qubits share the same physical error probability p.
    So all lambda_j_0 are the same. But in future implementation (circuit-level H),
    we need to initialize lambda_j_0[i] for each single column i of H. This should
    be generated by python and see as a compile-time constant in cpp.
    */
    

    /* ---- VNU initialization (before leg 0) ---- */
    vnu_state_type vnu_state[H_X_COLS];
    qec_lfsr_t seeds[H_X_COLS];
    rng_seed_all(seeds, qec_lfsr_t(seed));
    for (i = 0; i < H_X_COLS; i++){
        vnu_state[i].beta_int = RELAY_BETA_LEG_0;
        vnu_state[i].M_reg = lambda_j_0_int;
        vnu_state[i].lfsr = seeds[i];
    }

    /* ---- initialize parameters ---- */
    int e_hat_leg[H_X_COLS];
    int best_e_hat[H_X_COLS];
    int best_w = INT_MAX;   // should be 15*144=2160 when switched to int4
    int s = 0;
    int total_iters = 0;
    int legs_used = 0;
    int iters = 0;  // # of iterations before coming to a result
    int converged = 0;
    int T, w;

    for (r = 0; r <= RELAY_R; r++){

        T = (r == 0) ? RELAY_T0 : RELAY_TR;

        decode_leg(syndrome, cn_neighbor, vn_neighbor, vnu_state, lambda_j_0_int, T, (r == 0), (r >= 1), e_hat_leg, &iters, &converged);

        total_iters += iters;
        legs_used++;

        if (converged){
            w = solution_weight(e_hat_leg, lambda_j_0_int, H_X_COLS);
            s++;
            if (w < best_w){
                best_w = w;
                for (i=0;i<H_X_COLS;i++) best_e_hat[i] = e_hat_leg[i];
            }
            if (s >= RELAY_S) break; // found S solutions
        }

    }

    *num_sol_out = s;
    *total_iters_out = total_iters;
    *legs_used_out = legs_used;

    if(s > 0){  //there are solutions found
        for (i=0;i<H_X_COLS;i++) e_hat_out[i] = best_e_hat[i];
    } else {    // if no solution is found -> decoding failure
        for (i=0;i<H_X_COLS;i++) e_hat_out[i] = e_hat_leg[i];   // if fail, output the e_hat of the last leg

    }
    return (s>0);
}