/* Generated by export_bb_code.py -- do not edit by hand.
 * Regenerate with an interpreter that has qldpc installed:
 *     python export_bb_code.py
 */

#ifndef BB_CODE_DATA_H
#define BB_CODE_DATA_H

/* Gross code [[144,12,12]], X-type checks (H_x).  See
 * integrated_cnu_vnu/matrix_generator.py for the construction. */
#define NUM_CHECK_NODE     72
#define NUM_VARIABLE_NODE  144
#define CHECK_DEGREE       6    /* row weight of H    */
#define VARIABLE_DEGREE    3    /* column weight of H */
#define NUM_LOGICAL        12

/* check_node_neighbor[ii][d] -- the variable node on edge d of check node ii.
 * The nonzero positions of row ii of H, so it also serves as the sparse H. */
extern const int check_node_neighbor[NUM_CHECK_NODE][CHECK_DEGREE];

/* variable_node_neighbor[jj][d] -- the check node on edge d of variable node jj. */
extern const int variable_node_neighbor[NUM_VARIABLE_NODE][VARIABLE_DEGREE];

/* Slot tables: which element of the neighbour's output array carries this edge.
 * These replace the two list.index() lookups the Python decoder redoes every
 * iteration -- they are fixed by H, so they are computed once at export time. */
extern const int cnu_src_slot[NUM_CHECK_NODE][CHECK_DEGREE];
extern const int vnu_src_slot[NUM_VARIABLE_NODE][VARIABLE_DEGREE];

/* X-type logical operators; a decode is a logical success when
 * logical_A_x @ (e_hat ^ error) == 0 over GF(2). */
extern const int logical_A_x[NUM_LOGICAL][NUM_VARIABLE_NODE];

#endif /* BB_CODE_DATA_H */
