/* bp_decoder.h
 *
 * The BP iteration loop shared by iterations_bp.c, iterations_dmem_bp.c and
 * test_bp.c.  Plain BP and DMem-BP differ by exactly one block at the bottom
 * of the loop, so they are one function with a flag rather than two copies.
 *
 * Everything about the code itself -- Tanner graph, per-edge slot tables,
 * logical operators -- is a compile-time constant generated by
 * export_bb_code.py into bb_code_data.{h,c}.
 */

#ifndef BP_DECODER_H
#define BP_DECODER_H

#include "bb_code_data.h"

#define BP_MAX_ITERATION 60

typedef struct {
    int syndrome[NUM_CHECK_NODE];        /* H @ error mod 2                  */
    int syndrome_check[NUM_CHECK_NODE];  /* H @ e_hat mod 2                  */
    int e_hat[NUM_VARIABLE_NODE];        /* estimated error                  */
    int iterations;                      /* t at which the loop stopped      */
    int converged;                       /* syndrome consistency only        */
    int logical_success;                 /* A_x @ (e_hat ^ error) == 0       */
    int decode_success;                  /* logical_success && converged     */
} bp_result;

/* out = (H @ vec) mod 2.
 * H is stored sparsely as check_node_neighbor, so this is an XOR over the
 * CHECK_DEGREE variable nodes on each row. */
void bp_syndrome(const int *vec, int *out);

/* out = (logical_A_x @ vec) mod 2, NUM_LOGICAL entries. */
void bp_logical_action(const int *vec, int *out);

/* Run min-sum BP on one error pattern.
 *     error       : NUM_VARIABLE_NODE entries, 0 or 1
 *     lambda_int  : scaled error prior, Lambda_j(0)
 *     use_dmem    : 0 = plain BP, 1 = DMem-BP (error prior updated each pass) */
void bp_decode(const int *error, int lambda_int, int use_dmem, bp_result *result);

/* Reporting helper shared by the two decoder programs. */
void bp_print_vector(const char *label, const int *v, int count);

#endif /* BP_DECODER_H */
