/* Generated by export_bb_code.py -- do not edit by hand.
 * Regenerate with an interpreter that has qldpc installed:
 *     python export_bb_code.py
 */

#ifndef BP_TEST_DATA_H
#define BP_TEST_DATA_H

#include "bb_code_data.h"

/* Decode cases with the results the Python reference produces.
 * Case 0 is (p=0.1, seed=21), the case iterations_bp.py runs. */
#define NUM_TEST_CASES 21

extern const double test_p[NUM_TEST_CASES];
extern const int test_seed[NUM_TEST_CASES];
extern const int test_lambda_int[NUM_TEST_CASES];
extern const int test_error[NUM_TEST_CASES][NUM_VARIABLE_NODE];

extern const int golden_bp_iterations[NUM_TEST_CASES];
extern const int golden_bp_converged[NUM_TEST_CASES];
extern const int golden_bp_success[NUM_TEST_CASES];
extern const int golden_bp_e_hat[NUM_TEST_CASES][NUM_VARIABLE_NODE];

extern const int golden_dmem_iterations[NUM_TEST_CASES];
extern const int golden_dmem_converged[NUM_TEST_CASES];
extern const int golden_dmem_success[NUM_TEST_CASES];
extern const int golden_dmem_e_hat[NUM_TEST_CASES][NUM_VARIABLE_NODE];

#endif /* BP_TEST_DATA_H */
